### PR TITLE
Update CSS -> Now SCSS

### PR DESCRIPTION
**Pull request by venarius**
Updated the primer.css to their newest version (v9.1.1). It's now in the .scss file format. Also changed the version to '0.5.0'.

### CODE REVIEW

**Comment by piotrjaworski** [comment]
@venarius Thank you for your contribution! What about adding new styles as a CSS file? Not everyone uses CSS preprocessors like Sass.

**Comment by venarius** [comment]
@piotrjaworski Well, since primer-css is now written in Sass, it'll be kinda hard to convert these files into css. But I can try to do so, if you want!

EDIT: Just found out that I can simply interpret it with Rails. I will be doing that later!

**Comment by piotrjaworski** [comment]
@venarius There are two options - add a Sass preprocessor as a dependency to the gem or add a css file :)

**Comment by venarius** [comment]
@piotrjaworski Thank you for your tips :) I now replaced the SCSS file with a CSS file. It keeps the gem more compatible.

**Pull request merged**
